<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        Product::query()->delete();

        Product::query()->insert([
            [
                'slug' => 'solstice-floor-lamp',
                'name' => 'Đèn sàn Solstice',
                'category' => 'Ánh sáng',
                'tagline' => 'Thép ánh đồng, chụp vải linen ấm và quầng sáng hổ phách dài.',
                'description' => 'Mẫu đèn đọc sách cao dáng thanh, tạo vùng sáng dịu cho phòng khách, studio và góc thư giãn. Thân đèn giữ nét kiến trúc gọn gàng, còn chụp linen mang lại cảm giác ấm và ở lâu không chán.',
                'price' => 10900000.00,
                'compare_price' => 12400000.00,
                'rating' => 4.9,
                'reviews_count' => 38,
                'badge' => 'Bán chạy',
                'image_url' => '/storage/products/solstice-floor-lamp_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/solstice-floor-lamp_0.jpg',
                    '/storage/products/solstice-floor-lamp_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Đế đá nặng cho cảm giác đứng vững và chắc tay',
                    'Công tắc kéo bằng đồng, tương thích bóng LED 2700K',
                    'Thân đèn sơn tĩnh điện với chi tiết ánh đồng chải xước',
                ]),
                'specs' => json_encode([
                    'Hoàn thiện' => 'Đồng chải xước và linen',
                    'Chiều cao' => '162 cm',
                    'Giao hàng' => 'Gửi trong 3 ngày làm việc',
                ]),
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'vale-boucle-lounge-chair',
                'name' => 'Ghế lounge Vale Bouclé',
                'category' => 'Nội thất',
                'tagline' => 'Dáng ngồi thấp, phom uốn khối và khung sồi sẫm màu.',
                'description' => 'Vale được làm cho những buổi tối chậm rãi: đệm dày, tay cong mềm và độ ngả vừa đủ để thư giãn nhưng vẫn giữ tư thế đẹp. Mẫu ghế đem cảm giác gallery vào không gian ở hằng ngày.',
                'price' => 22800000.00,
                'compare_price' => 24900000.00,
                'rating' => 4.8,
                'reviews_count' => 24,
                'badge' => 'Studio chọn',
                'image_url' => '/storage/products/vale-boucle-lounge-chair_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/vale-boucle-lounge-chair_0.jpg',
                    '/storage/products/vale-boucle-lounge-chair_0.jpg',
                ]),
                'highlights' => json_encode([
                    'Vải bouclé bền cho sử dụng hằng ngày',
                    'Khung gỗ sồi sấy khô phủ dầu mờ',
                    'Độ sâu mặt ngồi tối ưu cho đọc sách và lounge',
                ]),
                'specs' => json_encode([
                    'Chất liệu' => 'Gỗ sồi, foam, bouclé',
                    'Bề ngang' => '84 cm',
                    'Dịch vụ' => 'Có hỗ trợ giao và lắp đặt tận nơi',
                ]),
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'tidal-pour-over-set',
                'name' => 'Bộ pour-over Tidal',
                'category' => 'Gốm sứ',
                'tagline' => 'Phễu lọc và bình server stoneware phủ men muối biển mờ.',
                'description' => 'Bộ pha cà phê hai món dành cho những buổi sáng có nhịp chậm. Phễu lọc đặt gọn vào bình server, giúp nghi thức pha cà phê sạch sẽ, gọn và đủ đẹp để trưng ngay trên kệ bếp.',
                'price' => 2950000.00,
                'compare_price' => null,
                'rating' => 4.9,
                'reviews_count' => 67,
                'badge' => 'Mới',
                'image_url' => '/storage/products/tidal-pour-over-set_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/tidal-pour-over-set_0.jpg',
                    '/storage/products/tidal-pour-over-set_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Stoneware hoàn thiện thủ công với độ loang men nhẹ',
                    'Tương thích giấy lọc tiêu chuẩn',
                    'Tay cầm cân bằng, miệng rót chống nhỏ giọt',
                ]),
                'specs' => json_encode([
                    'Dung tích' => '700 ml',
                    'Bảo quản' => 'Dùng được với máy rửa chén',
                    'Xuất xứ' => 'Sản xuất tại Kyoto',
                ]),
                'is_featured' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'dune-linen-throw',
                'name' => 'Khăn choàng linen Dune',
                'category' => 'Vải vóc',
                'tagline' => 'Sợi lanh thoáng nhẹ với dải clay đã giặt mềm.',
                'description' => 'Khăn choàng khổ lớn dành cho khí hậu ấm và những không gian thích layering. Chất liệu nhẹ, thoáng và có cảm giác đã dùng quen ngay từ ngày đầu tiên.',
                'price' => 2300000.00,
                'compare_price' => 2750000.00,
                'rating' => 4.7,
                'reviews_count' => 44,
                'badge' => null,
                'image_url' => '/storage/products/dune-linen-throw_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/dune-linen-throw_0.jpg',
                    '/storage/products/dune-linen-throw_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Lanh châu Âu đã garment-wash',
                    'Mép tua mềm cho cảm giác thoải mái tự nhiên',
                    'Đủ nhẹ để dùng quanh năm',
                ]),
                'specs' => json_encode([
                    'Kích thước' => '140 x 200 cm',
                    'Màu sắc' => 'Cát nhạt và clay',
                    'Bảo quản' => 'Giặt máy nước lạnh',
                ]),
                'is_featured' => false,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'halo-travertine-side-table',
                'name' => 'Bàn phụ travertine Halo',
                'category' => 'Nội thất',
                'tagline' => 'Khối đá tròn tối giản cho sofa, giường ngủ và góc đọc sách.',
                'description' => 'Bàn phụ kích thước gọn với mặt travertine vân tự nhiên và chân trụ tạo bóng đổ đẹp. Những lỗ rỗ và chuyển sắc nhỏ giúp mỗi chiếc đều có cá tính riêng.',
                'price' => 14600000.00,
                'compare_price' => null,
                'rating' => 4.8,
                'reviews_count' => 19,
                'badge' => 'Giới hạn',
                'image_url' => '/storage/products/halo-travertine-side-table_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/halo-travertine-side-table_0.jpg',
                    '/storage/products/halo-travertine-side-table_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Mặt đá travertine honed',
                    'Đế có đệm cao su cho sàn cứng',
                    'Dùng đẹp như bàn phụ, bục trưng bày hoặc tab đầu giường',
                ]),
                'specs' => json_encode([
                    'Loại đá' => 'Travertine Roman',
                    'Chiều cao' => '48 cm',
                    'Khối lượng' => '21 kg',
                ]),
                'is_featured' => true,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'ember-reed-diffuser',
                'name' => 'Tinh dầu que Ember',
                'category' => 'Hương thơm',
                'tagline' => 'Gỗ tuyết tùng cháy nhẹ, trà đen và cam bergamot dịu.',
                'description' => 'Mùi hương không gian thiên gỗ, khô và sâu, phù hợp cho lối vào, phòng ngủ hoặc studio. Vừa đủ sáng để căn phòng thoáng hơn nhưng vẫn giữ được chiều sâu.',
                'price' => 1680000.00,
                'compare_price' => null,
                'rating' => 4.8,
                'reviews_count' => 83,
                'badge' => 'Vừa về',
                'image_url' => '/storage/products/ember-reed-diffuser_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/ember-reed-diffuser_0.jpg',
                    '/storage/products/ember-reed-diffuser_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Nền khuếch tán không cồn',
                    'Thời gian hương kéo dài khoảng 14 tuần',
                    'Thân chai thủy tinh khói với nắp mờ',
                ]),
                'specs' => json_encode([
                    'Tầng hương' => 'Tuyết tùng, trà đen, bergamot',
                    'Dung tích' => '180 ml',
                    'Cách dùng' => 'Khuếch tán liên tục',
                ]),
                'is_featured' => false,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'meridian-storage-basket',
                'name' => 'Giỏ lưu trữ Meridian',
                'category' => 'Lưu trữ',
                'tagline' => 'Cói đan tay với cổ da giữ phom chắc và gọn.',
                'description' => 'Một món lưu trữ đủ đẹp để đặt giữa không gian mở. Hợp để đựng khăn, tạp chí, đĩa than hoặc những vật dụng hằng ngày mà không khiến căn phòng trở nên quá công năng.',
                'price' => 1920000.00,
                'compare_price' => 2180000.00,
                'rating' => 4.6,
                'reviews_count' => 31,
                'badge' => null,
                'image_url' => '/storage/products/meridian-storage-basket_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/meridian-storage-basket_0.jpg',
                    '/storage/products/meridian-storage-basket_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Thân giỏ đan bằng cói sông',
                    'Chi tiết da thuộc thực vật',
                    'Vòng thép ẩn giúp thành giỏ giữ phom đẹp',
                ]),
                'specs' => json_encode([
                    'Đường kính' => '42 cm',
                    'Chiều cao' => '38 cm',
                    'Sử dụng' => 'Trong nhà',
                ]),
                'is_featured' => false,
                'sort_order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'aster-stoneware-bowl-set',
                'name' => 'Bộ bát stoneware Aster',
                'category' => 'Gốm sứ',
                'tagline' => 'Bốn bát gốm tạo hình tay cho trái cây, mì và món dùng chung.',
                'description' => 'Bộ bát xếp gọn với lớp men ngà lấm tấm và chiều sâu vừa đủ cho bữa ăn hằng ngày. Cầm nhẹ tay nhưng vẫn chắc chắn cho nhịp dùng liên tục.',
                'price' => 2150000.00,
                'compare_price' => null,
                'rating' => 4.9,
                'reviews_count' => 52,
                'badge' => 'Quà tặng yêu thích',
                'image_url' => '/storage/products/aster-stoneware-bowl-set_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/aster-stoneware-bowl-set_0.jpg',
                    '/storage/products/aster-stoneware-bowl-set_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Set 4 bát xếp chồng gọn',
                    'Men ngà lấm tấm với chân gốm thô',
                    'Trọng lượng cân bằng cho dùng mỗi ngày',
                ]),
                'specs' => json_encode([
                    'Bộ gồm' => '4 bát',
                    'Đường kính' => '16 cm',
                    'Bảo quản' => 'Dùng được lò vi sóng và máy rửa chén',
                ]),
                'is_featured' => false,
                'sort_order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'arc-wall-sconce',
                'name' => 'Đèn tường Arc',
                'category' => 'Ánh sáng',
                'tagline' => 'Thép đen mờ với bóng đèn Edison ấm.',
                'description' => 'Đèn tường thiết kế tối giản cho phòng ngủ, lối vào hoặc góc đọc sách. Bóng đèn Edison tạo ánh sáng ấm dịu, hoàn hảo cho không gian thư giãn.',
                'price' => 3450000.00,
                'compare_price' => 3850000.00,
                'rating' => 4.7,
                'reviews_count' => 29,
                'badge' => 'Bán chạy',
                'image_url' => '/storage/products/arc-wall-sconce_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/arc-wall-sconce_0.jpg',
                    '/storage/products/arc-wall-sconce_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Thép đen mờ hoàn thiện',
                    'Bóng đèn Edison 2700K đi kèm',
                    'Công tắc dây kéo cổ điển',
                ]),
                'specs' => json_encode([
                    'Hoàn thiện' => 'Đen mờ',
                    'Chiều cao' => '28 cm',
                    'Giao hàng' => 'Gửi trong 3 ngày làm việc',
                ]),
                'is_featured' => true,
                'sort_order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'velvet-throw-pillow',
                'name' => 'Gối nhung Velvet',
                'category' => 'Vải vóc',
                'tagline' => 'Nhung mềm với màu xanh cổ vịt đậm.',
                'description' => 'Gối nhung cao cấp thêm chiều sâu và sang trọng cho sofa hoặc giường ngủ. Chất liệu mềm mại, thoải mái khi tựa lưng.',
                'price' => 890000.00,
                'compare_price' => null,
                'rating' => 4.6,
                'reviews_count' => 37,
                'badge' => null,
                'image_url' => '/storage/products/velvet-throw-pillow_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/velvet-throw-pillow_0.jpg',
                    '/storage/products/velvet-throw-pillow_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Nhung 100% polyester',
                    'Lót bông mật độ cao',
                    'Có thể giặt máy',
                ]),
                'specs' => json_encode([
                    'Kích thước' => '50 x 50 cm',
                    'Màu sắc' => 'Xanh cổ vịt',
                    'Bảo quản' => 'Giặt máy nước lạnh',
                ]),
                'is_featured' => false,
                'sort_order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'ceramic-vase-set',
                'name' => 'Bộ bình gốm Ceramic',
                'category' => 'Gốm sứ',
                'tagline' => 'Ba bình gốm với men trắng mờ.',
                'description' => 'Bộ ba bình gốm với kích thước khác nhau, hoàn hảo cho hoa khô hoặc trưng bày đơn giản. Men trắng mờ tạo vẻ đẹp tinh tế.',
                'price' => 2850000.00,
                'compare_price' => 3200000.00,
                'rating' => 4.8,
                'reviews_count' => 42,
                'badge' => 'Studio chọn',
                'image_url' => '/storage/products/ceramic-vase-set_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/ceramic-vase-set_0.jpg',
                    '/storage/products/ceramic-vase-set_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Set 3 bình kích thước khác nhau',
                    'Men trắng mờ thủ công',
                    'Phù hợp hoa khô và tươi',
                ]),
                'specs' => json_encode([
                    'Bộ gồm' => '3 bình',
                    'Chiều cao' => '20-35 cm',
                    'Bảo quản' => 'Dùng được máy rửa chén',
                ]),
                'is_featured' => true,
                'sort_order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'wooden-serving-tray',
                'name' => 'Khay phục vụ gỗ',
                'category' => 'Lưu trữ',
                'tagline' => 'Gỗ sồi tự nhiên với tay cầm.',
                'description' => 'Khay phục vụ bằng gỗ sồi tự nhiên, hoàn hảo cho trà, cà phê hoặc phục vụ đồ ăn. Tay cầm tiện lợi và thiết kế sang trọng.',
                'price' => 1450000.00,
                'compare_price' => null,
                'rating' => 4.5,
                'reviews_count' => 28,
                'badge' => null,
                'image_url' => '/storage/products/wooden-serving-tray_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/wooden-serving-tray_0.jpg',
                    '/storage/products/wooden-serving-tray_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Gỗ sồi tự nhiên',
                    'Tay cầm tiện lợi',
                    'Đáy chống trượt',
                ]),
                'specs' => json_encode([
                    'Kích thước' => '40 x 28 cm',
                    'Chất liệu' => 'Gỗ sồi',
                    'Bảo quản' => 'Lau bằng vải mềm',
                ]),
                'is_featured' => false,
                'sort_order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'lavender-candle',
                'name' => 'Nến hương Lavender',
                'category' => 'Hương thơm',
                'tagline' => 'Nến sáp đậu nành với tinh dầu lavender.',
                'description' => 'Nến sáp đậu nành tự nhiên với tinh dầu lavender tinh khiết. Tạo không gian thư giãn, giúp giảm căng thẳng và cải thiện giấc ngủ.',
                'price' => 780000.00,
                'compare_price' => 890000.00,
                'rating' => 4.9,
                'reviews_count' => 95,
                'badge' => 'Bán chạy',
                'image_url' => '/storage/products/lavender-candle_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/lavender-candle_0.jpg',
                    '/storage/products/lavender-candle_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Sáp đậu nành 100% tự nhiên',
                    'Tinh dầu lavender tinh khiết',
                    'Thời gian cháy khoảng 40 giờ',
                ]),
                'specs' => json_encode([
                    'Trọng lượng' => '200g',
                    'Thời gian cháy' => '40 giờ',
                    'Mùi hương' => 'Lavender',
                ]),
                'is_featured' => false,
                'sort_order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'linen-table-runner',
                'name' => 'Khăn trải bàn linen',
                'category' => 'Vải vóc',
                'tagline' => 'Lanh tự nhiên với màu đất ấm.',
                'description' => 'Khăn trải bàn bằng lanh tự nhiên, hoàn hảo cho bàn ăn hoặc bàn trà. Màu đất ấm tạo cảm giác gần gũi và thư giãn.',
                'price' => 1250000.00,
                'compare_price' => null,
                'rating' => 4.6,
                'reviews_count' => 33,
                'badge' => null,
                'image_url' => '/storage/products/linen-table-runner_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/linen-table-runner_0.jpg',
                    '/storage/products/linen-table-runner_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Lanh 100% tự nhiên',
                    'Màu đất ấm',
                    'Có thể giặt máy',
                ]),
                'specs' => json_encode([
                    'Kích thước' => '160 x 40 cm',
                    'Màu sắc' => 'Đất',
                    'Bảo quản' => 'Giặt máy nước lạnh',
                ]),
                'is_featured' => false,
                'sort_order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'marble-coaster-set',
                'name' => 'Bộ lót ly marble',
                'category' => 'Lưu trữ',
                'tagline' => 'Marble trắng với vân tự nhiên.',
                'description' => 'Bộ 6 lót ly bằng marble trắng với vân tự nhiên. Sang trọng và bền đẹp, hoàn hảo cho bàn ăn hoặc phòng khách.',
                'price' => 1650000.00,
                'compare_price' => 1890000.00,
                'rating' => 4.7,
                'reviews_count' => 41,
                'badge' => null,
                'image_url' => '/storage/products/marble-coaster-set_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/marble-coaster-set_0.jpg',
                    '/storage/products/marble-coaster-set_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Marble trắng tự nhiên',
                    'Vân marble độc đáo',
                    'Đế chống trượt',
                ]),
                'specs' => json_encode([
                    'Bộ gồm' => '6 chiếc',
                    'Kích thước' => '10 x 10 cm',
                    'Chất liệu' => 'Marble',
                ]),
                'is_featured' => false,
                'sort_order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'ceramic-teapot',
                'name' => 'Bình trà gốm',
                'category' => 'Gốm sứ',
                'tagline' => 'Bình trà với men xanh cổ vịt.',
                'description' => 'Bình trà gốm thủ công với men xanh cổ vịt đẹp mắt. Hoàn hảo cho buổi trà chiều hoặc trưng bày.',
                'price' => 2450000.00,
                'compare_price' => null,
                'rating' => 4.8,
                'reviews_count' => 36,
                'badge' => 'Mới',
                'image_url' => '/storage/products/ceramic-teapot_0.jpg',
                'gallery' => json_encode([
                    '/storage/products/ceramic-teapot_0.jpg',
                    '/storage/products/ceramic-teapot_1.jpg',
                ]),
                'highlights' => json_encode([
                    'Gốm thủ công',
                    'Men xanh cổ vịt',
                    'Dung tích 800ml',
                ]),
                'specs' => json_encode([
                    'Dung tích' => '800 ml',
                    'Màu sắc' => 'Xanh cổ vịt',
                    'Bảo quản' => 'Dùng được máy rửa chén',
                ]),
                'is_featured' => false,
                'sort_order' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
